### PR TITLE
Add item delete button

### LINKED ISSUE #41: Request: Add a delete button to the item window
This is a feature request.

I am using the Data Manager in conjunction with contact and other submission forms. So, any time a form is submitted, the contents are saved to the user>data folder as well as being emailed. This is handy as a reference in case the form is not received or lost, and also as a permanent record of a response eg agreeing to terms and conditions.

It is all working well with Grav 1.7.26. However, I thought it would be nice to have a way to delete items that you don't want. The main use case would be removing spam messages that are sent thought the email contact form.

### PR DESCRIPTION
**Pull request by Karmalakas**
Adds delete button to list and item templates
Handled with item URL query `?delete`

**NB:** No confirmation dialog - item gets deleted right after click

image
image
image
image

Closes #41

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for doing this! I have just been testing the changes. A couple of things I noticed...

1. I am not getting this button text showing correctly: 
```
 <div class="button-bar danger">
        <a href="{{ type }}.csv" class="button">{{ "PLUGIN_DATA_MANAGER.DOWNLOAD_AS"|t }} CSV</a>
 </div>
```
When I installed the 1.3.0 version of the plugin it had the actual text ("Download as CSV") in there. May be something wrong at my end but your version now looks like this for me:
items-list

2. On the individual item page clicking the trash button takes me back to the items list, but the item isn't deleted. It is still on the list and can be re-accessed. It does delete from the main list, so I am assuming it's not some sort of permissions problem.

**Comment by ghost** [comment]
So I think the problem is that the link in the item window is leaving off the .txt part.

So when I hover over the trash icon it shows ... `contact/contact-20220105-172648-512205?delete`

and it needs to be `contact/contact-20220105-172648-512205.txt?delete`

**Comment by w00fz** [comment]
Can you try https://github.com/getgrav/grav-plugin-data-manager/archive/refs/tags/1.4.0.zip instead?

I actually made some small changes and Im not sure you are using the right version now

**Comment by w00fz** [comment]
Can you try https://github.com/getgrav/grav-plugin-data-manager/archive/refs/tags/1.4.0.zip instead?

I actually made some small changes and Im not sure you are using the right version now

**Comment by ghost** [comment]
The button text is good now.

I still have the problem with item delete not working. It doesn't pick up on adding the .txt to the file name.

And yet in the item list it does.

**Comment by ghost** [comment]
Ah. It does work correctly if I use yaml format. So it's a problem with .txt

**Comment by w00fz** [comment]
Yeah I just noticed that too, json, html and yaml all seem to work fine, only txt doesn't for some reason. The extension is there but the filename display omits it.

**Comment by w00fz** [comment]
@simplycomputing I released v1.4.1 which should take care of this. Please let me know, thanks!

**Comment by ghost** [comment]
Yes! All working perfectly now. Thanks for your efforts @w00fz and @Karmalakas

**Pull request merged**
